openapi: 3.0.3
info:
  title: Unified Textbook Generation and RAG System API
  description: API for the Unified Physical AI & Humanoid Robotics Learning Book project
  version: 1.0.0
servers:
  - url: https://api.unifiedbook.example.com
    description: Production server
  - url: https://staging-api.unifiedbook.example.com
    description: Staging server
paths:
  /api/chapters/import:
    post:
      summary: Import Claude-generated textbook chapters
      description: Import textbook chapters into the Docusaurus structure
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_path:
                  type: string
                  description: Path to the source textbook files
                destination_path:
                  type: string
                  description: Destination path in docs folder
                options:
                  type: object
                  properties:
                    validate_frontmatter:
                      type: boolean
                      description: Whether to validate frontmatter during import
                    create_missing_frontmatter:
                      type: boolean
                      description: Whether to create missing frontmatter fields
      responses:
        '200':
          description: Chapters imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  imported_count:
                    type: integer
                  errors:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error

  /api/chapters/{chapterId}:
    get:
      summary: Retrieve a specific chapter
      description: Get chapter content with proper formatting
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the chapter
      responses:
        '200':
          description: Chapter retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapter_id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  frontmatter:
                    type: object
                  order:
                    type: integer
        '404':
          description: Chapter not found
        '500':
          description: Internal server error

  /api/chat/query:
    post:
      summary: Process user queries with RAG
      description: Process user questions using Retrieval-Augmented Generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - user_id
              properties:
                query:
                  type: string
                  description: User's question
                user_id:
                  type: string
                  description: User identifier
                context_type:
                  type: string
                  enum: [full_book, selected_text]
                  description: Context for the query
                selected_text:
                  type: string
                  description: Text selected for context (if context_type is selected_text)
      responses:
        '200':
          description: Query processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                  context_used:
                    type: string
                  tokens_used:
                    type: integer
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error

  /api/auth/signup:
    post:
      summary: User registration with background questionnaire
      description: Register a new user with background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  description: User's full name
                email:
                  type: string
                  description: User's email address
                password:
                  type: string
                  description: User's password
                software_experience:
                  type: string
                  enum: [beginner, intermediate, expert]
                  description: User's software experience level
                hardware_availability:
                  type: string
                  description: Description of available hardware
                robotics_familiarity:
                  type: string
                  enum: [beginner, intermediate, expert]
                  description: User's robotics familiarity level
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: Invalid input parameters
        '409':
          description: User with this email already exists
        '500':
          description: Internal server error

  /api/auth/signin:
    post:
      summary: User sign-in
      description: Authenticate user and return access tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                description: User's email address
              password:
                type: string
                description: User's password
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: Invalid input parameters
        '401':
          description: Invalid credentials
        '500':
          description: Internal server error

  /api/translate:
    post:
      summary: Translate content to Urdu
      description: Translate text content to Urdu language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
                - target_language
              properties:
                text:
                  type: string
                  description: Text to translate
                target_language:
                  type: string
                  default: ur
                  description: Target language code (ur for Urdu)
      responses:
        '200':
          description: Translation completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_text:
                    type: string
                  translated_text:
                    type: string
                  source_language:
                    type: string
                  target_language:
                    type: string
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error

  /api/chapters/{chapterId}/personalize:
    put:
      summary: Personalize chapter content
      description: Adjust chapter content based on user preferences
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the chapter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: User identifier
                difficulty_level:
                  type: string
                  enum: [beginner, intermediate, expert]
                content_preferences:
                  type: object
                  description: User's content preferences
      responses:
        '200':
          description: Chapter personalized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalized_content:
                    type: string
        '400':
          description: Invalid input parameters
        '500':
          description: Internal server error

components:
  schemas:
    Chapter:
      type: object
      properties:
        chapter_id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Chapter title
        content:
          type: string
          description: Markdown content of the chapter
        frontmatter:
          type: object
          description: Frontmatter data including id, title, sidebar_label
        order:
          type: integer
          description: Sequence order of the chapter in the book
        path:
          type: string
          description: Relative path in docs folder
        slug:
          type: string
          description: URL-friendly version of the title
        description:
          type: string
          description: Brief description of the chapter content
        created_at:
          type: string
          format: date-time
          description: Timestamp when chapter was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when chapter was last updated
      required:
        - chapter_id
        - title
        - content
        - order

    User:
      type: object
      properties:
        user_id:
          type: string
          description: Unique identifier for the user
        name:
          type: string
          description: User's full name
        email:
          type: string
          description: User's email address
        software_experience:
          type: string
          enum: [beginner, intermediate, expert]
          description: User's software experience level
        hardware_availability:
          type: string
          description: Description of available hardware
        robotics_familiarity:
          type: string
          enum: [beginner, intermediate, expert]
          description: User's robotics familiarity level
        created_at:
          type: string
          format: date-time
          description: Timestamp when user registered
        updated_at:
          type: string
          format: date-time
          description: Timestamp when user profile was last updated
      required:
        - user_id
        - name
        - email