import json
import os
from typing import Dict, List, Any
from pathlib import Path

from sqlalchemy.orm import Session

from src.services.chapter_service import ChapterService


class SidebarsGenerator:
    """Utility class for generating Docusaurus sidebar configuration based on chapter order."""

    @staticmethod
    def generate_sidebar_from_database(db: Session, docs_path: str = "../my-website/docs/physical-ai/") -> Dict[str, Any]:
        """
        Generate sidebar configuration based on chapters in the database.

        Args:
            db: Database session
            docs_path: Path to the docs directory

        Returns:
            Dictionary representing the sidebar configuration
        """
        # Get all chapters ordered by sequence
        chapters = ChapterService.get_chapters_by_docs_folder(db, docs_path)

        # Sort chapters by order
        sorted_chapters = sorted(chapters, key=lambda x: x.order if x.order is not None else 9999)

        # Generate sidebar items
        sidebar_items = []
        for chapter in sorted_chapters:
            # Convert the chapter path to sidebar format
            # Remove the docs_path prefix and file extension
            relative_path = chapter.path.replace(docs_path, "").replace(".md", "").replace(".mdx", "")

            sidebar_items.append({
                "type": "doc",
                "id": chapter.slug,
                "label": chapter.title
            })

        # Create the full sidebar configuration
        sidebar_config = {
            "tutorialSidebar": [
                {
                    "type": "autogenerated",
                    "dirName": "."
                }
            ]
        }

        # If we have specific chapters, replace the autogenerated with specific items
        if sidebar_items:
            sidebar_config = {
                "tutorialSidebar": sidebar_items
            }

        return sidebar_config

    @staticmethod
    def generate_sidebar_from_filesystem(docs_path: str = "../my-website/docs/physical-ai/") -> Dict[str, Any]:
        """
        Generate sidebar configuration based on markdown files in the filesystem.

        Args:
            docs_path: Path to the docs directory

        Returns:
            Dictionary representing the sidebar configuration
        """
        path = Path(docs_path)
        if not path.exists():
            raise FileNotFoundError(f"Docs directory does not exist: {docs_path}")

        # Find all markdown files
        md_files = list(path.glob("*.md")) + list(path.glob("*.mdx"))

        # Extract frontmatter to get titles and order
        sidebar_items = []
        for file_path in md_files:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Extract frontmatter
            frontmatter = SidebarsGenerator._extract_frontmatter(content)

            # Use order from frontmatter if available, otherwise use filename
            order = frontmatter.get('order', 9999)
            title = frontmatter.get('title', file_path.stem)
            sidebar_label = frontmatter.get('sidebar_label', title)

            sidebar_items.append({
                "type": "doc",
                "id": file_path.stem,
                "label": sidebar_label,
                "order": order
            })

        # Sort by order
        sorted_items = sorted(sidebar_items, key=lambda x: x["order"])

        # Remove the order field as it's just for sorting
        for item in sorted_items:
            del item["order"]

        # Create the full sidebar configuration
        sidebar_config = {
            "tutorialSidebar": sorted_items
        }

        return sidebar_config

    @staticmethod
    def _extract_frontmatter(content: str) -> Dict[str, Any]:
        """
        Extract frontmatter from markdown content.

        Args:
            content: Markdown content with potential frontmatter

        Returns:
            Dictionary containing frontmatter data
        """
        import re
        import yaml

        # Look for YAML frontmatter between --- delimiters
        pattern = r'^---\n(.*?)\n---\n(.*)'
        match = re.match(pattern, content, re.DOTALL)

        if match:
            frontmatter_yaml = match.group(1)
            try:
                frontmatter = yaml.safe_load(frontmatter_yaml)
                if frontmatter is None:
                    frontmatter = {}
            except yaml.YAMLError:
                # If YAML parsing fails, treat as no frontmatter
                return {}
        else:
            # No frontmatter found
            frontmatter = {}

        return frontmatter

    @staticmethod
    def save_sidebar_config(sidebar_config: Dict[str, Any], output_path: str = "../my-website/sidebars.js"):
        """
        Save the sidebar configuration to a JavaScript file.

        Args:
            sidebar_config: Dictionary representing the sidebar configuration
            output_path: Path to save the sidebar configuration
        """
        # Convert the Python dict to JavaScript object notation
        js_content = "// @ts-check\n\n"
        js_content += "/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */\n"
        js_content += "const sidebars = "
        js_content += json.dumps(sidebar_config, indent=2)
        js_content += ";\n\n"
        js_content += "module.exports = sidebars;\n"

        # Write to file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(js_content)

        print(f"Sidebar configuration saved to {output_path}")

    @staticmethod
    def generate_and_save_sidebar_from_database(
        db: Session,
        docs_path: str = "../my-website/docs/physical-ai/",
        output_path: str = "../my-website/sidebars.js"
    ) -> None:
        """
        Generate and save sidebar configuration from database.

        Args:
            db: Database session
            docs_path: Path to the docs directory
            output_path: Path to save the sidebar configuration
        """
        sidebar_config = SidebarsGenerator.generate_sidebar_from_database(db, docs_path)
        SidebarsGenerator.save_sidebar_config(sidebar_config, output_path)

    @staticmethod
    def generate_and_save_sidebar_from_filesystem(
        docs_path: str = "../my-website/docs/physical-ai/",
        output_path: str = "../my-website/sidebars.js"
    ) -> None:
        """
        Generate and save sidebar configuration from filesystem.

        Args:
            docs_path: Path to the docs directory
            output_path: Path to save the sidebar configuration
        """
        sidebar_config = SidebarsGenerator.generate_sidebar_from_filesystem(docs_path)
        SidebarsGenerator.save_sidebar_config(sidebar_config, output_path)


# Example usage
if __name__ == "__main__":
    # This would typically be called from a management command
    # Example:
    # generator = SidebarsGenerator()
    # generator.generate_and_save_sidebar_from_filesystem()
    pass